Kaixo Nere, lehenengo sprint-a:  XML dokumentua, Proiektuaren egitura eta html egitura
Nereee/E4_ML_T1 pull request #1
Opened 2024-04-19 14:00 UTC by Mikel-elorrieta

2024-04-21 14:42 UTC, Nereee requested changes
XML fitxategiak egitura zuzena du. 
Web gunearen egitura eta diseinua ere zuzenak dira. 
Proiektuaren egitura fisikoa ez da zuzena: adibidez html karpeta barruan ezin dira irudiak eta xml egon, bi hauek kanpoan egon beharko lukete, karpeta nagusian. Eta scrip_php izatez egon daiteke html fitxategiekin... non jarriko dituzue xsl fitxategiak adibidez?
Eman buelta bat horri.

2024-04-22 06:49 UTC, Mikel-elorrieta commented
Egunon Nere, proiektuaren egitura fisikoa aldatu egin dugu. 
![diseinu Fisikoa](https://github.com/Nereee/E4_ML_T1/assets/157016292/8a1f38c7-7fb4-4eb7-b823-b48ac29e5df7)

2024-04-22 07:02 UTC, Nereee commented
XSL dokumentuak HTML maila berean egotea da normalagoa. Eta departamentua deitu duzuen horretan datuak eta euren baliozkotzea (xsd)
Eta js fitxategiak beste karpeta batean javascript izango direla. Baina ez dut ulertzen zergatik php barruan...

2024-04-22 07:18 UTC, Mikel-elorrieta commented
Aldaketa berriro egin dugu, egitura fisikoarena

2024-04-22 07:39 UTC, Nereee commented
Kontuz!! index.html dokumentua beti karpeta nagusian!!!!!! Zuzendu

2024-04-22 07:47 UTC, Mikel-elorrieta commented
Index-a aldatuta, karpetetan txt bat jarrita karpeta hutsak ez ezabatzearren

2024-04-22 08:49 UTC, Nereee approved these changes

2024-04-22 08:49 UTC, merged