Sprint2
Nereee/E4_ML_T1 pull request #2
Opened 2024-04-29 08:27 UTC by Iraitz-Elorrieta

Departamentuak eta Langileak erakutsi (XSL).  Departamentuen datuak eta langileen datuak erakutsi (XSL).

2024-04-29 09:51 UTC, Nereee requested changes
Departamentuak ez dira moldagarriak, agian langileen erara antolatu ahal dituzue. 
Eta datuen zerrendan, bai langileenean zein departamentuarenean, argibide batzuk jarri, ez dago argi datu bakoitza zer den

2024-04-30 07:09 UTC, Iraitz-Elorrieta commented
Langile eta departamentuetan datuak identefikatuta daude eta departamentuen css arazoak conponduta.

2024-04-30 07:35 UTC, Nereee reviewed
Responsive da. Baina finkatzerakoan zutabe kopurua 4-ra, beti, agindu honekin: grid-template-columns: repeat(4, minmax(min(150px, 100%), 0.2fr));
Kutxak oso txikiak ikusten dira.  Agian dinamikoagoa egin ahal duzue...
Zuen esanetara horrela utzi edo ez....

2024-04-30 10:16 UTC, Iraitz-Elorrieta commented
Css- a responsive da guztiz

2024-05-02 06:06 UTC, Nereee approved these changes

2024-05-02 06:07 UTC, Nereee commented
Oso ondo! errepasatu orri nagusian apurtutako estekaren bat dago eta.

2024-05-02 06:07 UTC, merged